name: flex_my_way
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  http: ^0.13.4
  intl: ^0.18.0
  url_launcher: ^6.0.20
  flutter_iconly: ^1.0.2
  shared_preferences: ^2.0.13
  sqflite: any
  path_provider: ^2.0.9
  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.1.2
  webview_flutter: ^4.0.2
  animated_text_kit: ^4.2.1
  image_picker: ^0.8.4+11
  share_plus: ^6.3.0
  geocoding: ^2.0.4
  geolocator: ^9.0.1
  app_settings: ^4.1.5
  get: ^4.6.1
  flutter_spinkit: ^5.1.0
  contacts_service: ^0.6.3
  permission_handler: ^10.0.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  timer_count_down: ^2.2.1
  animate_do: ^3.0.2
  flutter_native_image: ^0.0.6+1
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/jpegs/
    - assets/images/svgs/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 700

    - family: Neon
      fonts:
        - asset: assets/fonts/Neon.ttf
          weight: 600

